config/routes.rb
require 'sidekiq/web'
  
Ask::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  resources :notifications, :only => [:index, :destroy]
  
  resources :tags
  resources :badges, only: [:index, :show]
  
  post 'markdown/preview' => "application#preview"
  
  resources :photos, only: [:create]
      
  resources :questions do
    resources :comments, :only => [:create, :destroy]
    resources :votes, :only => [:create]
    collection do 
      post :preview
      get '/:tags' => 'questions#index', as: :tagged_with, constraints: { tags: /tags\:(.*)/ }
      get '/:filter' => 'questions#index', :as => :filtered, 
        :constraints => { :filter => /all|unanswered|by_me|feed|preferred|contributed|expertise/ }
    end
    
    member do      
      post :follow
      post :solve
      post :unsolve
    end
    
    resources :answers, :only => [:create, :update, :destroy] do
      resources :comments, :only => [:create, :destroy]
      resources :votes, :only => [:create]
      member do
      end
    end
  end

  root :to => 'questions#index'

  devise_for :users, :controllers => { 
    omniauth_callbacks: "users/omniauth_callbacks", 
    registrations: "users" 
  }
  
  devise_scope :user do
    resources :users, :only => [:show] do
      member do
        post :follow
      end
      collection do
        get "auth/:provider/unbind", to: :auth_unbind, as: :unbind_auth
        get 'avatar'
        put 'crop'
      end
    end
  end

  

end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Taggable
  include Mongoid::Votable
  include Mongoid::Followable
  
  field :title,         type: String
  field :body,          type: String
  field :views_count,   type: Integer, default: 0  
  
  field :accepted,      type: Boolean, default: false
  field :closed,        type: Boolean, default: false
  field :closed_at,     type: Time    
  
  field :answers_count, type: Integer, default: 0
    
  validates_presence_of :title
  validates_length_of   :title, in: 5..100
  validates_length_of   :body, minimum: 5, allow_blank: true

  belongs_to :user, :inverse_of => :questions, :counter_cache => true
  belongs_to :node, :inverse_of => :questions, :counter_cache => true
  
  belongs_to :answered_with, :class_name => "Answer"
   
  has_many :answers, :dependent => :destroy  
  has_many :badges, :as => :badgable
  
  embeds_many :comments, as: :commentable, cascade_callbacks: true  
  
  index :node_id => 1
  
  scope :minimal, -> { without(:body, :answers, :comments) }
  scope :followed_by, ->(*users){ where :follower_ids.in => users.map(&:id) }

  def viewed!(ip)
    view_count_id = "#{self.id}-#{ip}"
    if ViewsCount.where({ identity: view_count_id }).first.nil?
      ViewsCount.create(identity: view_count_id)
      self.inc(:views_count, 1)
    end    
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController  
  load_and_authorize_resource :only => [:new, :edit, :create, :update, :destroy, :follow, :unfollow, :solve, :unsolve], :through => :current_node
 
  order_tabs :index => {
    newest: {
      created_at: :desc,
    },
    votes: {
      votes_average: :desc,
      views_count: :desc
    },
    activity: {
      updated_at: :desc,
      created_at: :desc
    },
    hot: {
      views_count: :desc
    },
    answers: {
      answers_count: :desc
    }
  }, :show => {
    newest: {
      created_at: :desc,
    },
    oldest: {
      created_at: :asc,
    },
    votes: {
      votes_average: :desc,
      views_count: :desc
    }
  }
   
  # GET /questions
  # GET /questions.json
  def index
    find_questions
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = current_node.questions.find(params[:id])
    @question.viewed!(request.remote_ip)
    @answers = (@question.answers.page params[:page]).order_by(current_order)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    #@question = Question.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    #@question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    #@question = Question.new(params[:question])
    #@question.node = current_node
    @question.user_id = current_user.id
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: t('alert.question.create_success', default: 'Question was successfully created.') }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    #@question = Question.find(params[:id])
    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: t('alert.question.update_success', default: 'Question was successfully updated.') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    #@question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
  
  def solve
    @answer = @question.answers.find(params[:answer_id])
    @question.answered_with = @answer if @question.answered_with.nil?
    @question.accepted = true
    
    if @question.save
      current_user.on_activity(:close_question, current_node)
      if current_user != @answer.user
        @answer.user.update_reputation(:answer_picked_as_solution, current_node)
      end     
    end
  end
  
  def unsolve
    @answer = @question.answers.find(params[:answer_id])
    @question.accepted = false
    @question.answered_with = nil if @question.answered_with == @answer
    
    @question.save 
  end  
  
  def follow
    if @question.followed_by?(current_user)
      @question.unfollowed_by!(current_user)
    else
      @question.followed_by!(current_user)
    end
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end  
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
  
  
end

app/views/questions/_editor_toolbar.html.erb
<div class="editor_toolbar">
  <div class="icons pull-right">
    <%= link_to "#", class: "add-photo-image", rel: "new_photo", title: "Add Image" do %>
      <i class="icon-picture"></i>
    <% end %>
  </div>
  <ul class="pills" style="clear:none;">
    <li class="edit active"><%= link_to(t("common.editor_toolbar_edit"), "#") %></li>
    <li class="preview"><%= link_to(t("common.editor_toolbar_preview"), "#") %></li>
  </ul>
</div>

app/views/questions/_form.html.erb
<div class="box question-form-box">
<% modal_view ||= true -%>
<%= simple_form_for @question do |f| %>
  <fieldset>
    <% unless modal_view -%>
      <legend><%= controller.action_name.capitalize %> Question</legend>
    <% end -%>
    <%= render "shared/error_messages", :target => @question %>
    <%= f.input :title, label: t("common.title"), input_html: { class: "xxlarge" } %>
    
    <div class="control-group edit_tools">
      <label class="control-label"></label>
      <div class="controls">
        <%= render "editor_toolbar" %>
      </div>
    </div>
    <%= f.input :body, label: t("common.body"), as: :text, 
      input_html:{ :class => "questions_editor closewarning xxlarge", :style => "height:300px" },
      :hint => "請使用 Markdown 格式編寫,可以試試用 <a href='http://mouapp.com' target='_blank'>Mou</a> 這個 App 来編寫。".html_safe %>
      
    <%= f.input :tags, label: t("common.tags"), collection: tag_list, include_blank: false, input_html: { class: 'chzn-select', :multiple => true } %>
    
    <div class="form-actions">
      <%= f.submit t("common.save"), :class => "btn btn-primary", 'data-disable-with' => t("common.saving") %>
      <%= link_to t("common.cancel"), questions_path, :class => "btn reset" %>
    </div>
  </fieldset>
<% end %>

  <div class="hide">
  <%= simple_form_for Photo.new, html: { class: "form-inline upload-photo-form" } do |f| %>
    <%= f.input :image, label: false, input_html: { class: "upload-photo-images" } %>
  <% end %>
  </div>
</div>

app/views/questions/_question.html.erb
<div class="row-fluid question">
  <div class="title span8">
    <h3><%= link_to question.title, question_path(question), title: truncate(question.body, :length => 160)%></h3>
    <div class="tags">          
      <% question.tags.each do|tag| -%>
        <%= link_to tag_name(tag), tagged_with_questions_path(tag), class: "tag" %>
      <% end -%>
    </div>
  </div>  
  <div class="short-summary span3 offset1">
    <% if question.answers_count >= 1 %>
      <%= content_tag :div, class: "answers stats-box shadow#{question.accepted ? ' marker' : ''}" do %>  
        <span class="item-count"><%= question.answers_count %></span>  
        <div><%= t("questions.units.answers", default: "answers") %></div> 
      <% end %>
    <% else %>
      <div class="answers stats-box">
        <span class="no-count"><%= t("questions.units.empty", default: "no") %></span>  
        <div><%= t("questions.units.answers", default: "answers") %></div> 
      </div>
    <% end %>

    <% if question.views_count >= 1 %>
      <div class="views stats-box shadow">
        <span class="item-count"><%= question.views_count %></span>  
        <div><%= t("questions.units.views", default: "views") %></div> 
      </div>
    <% else %>
      <div class="views stats-box">
        <span class="no-count"><%= t("questions.units.empty", default: "no") %></span>  
        <div><%= t("questions.units.views", default: "views") %></div> 
      </div>
    <% end %>

    <% if question.votes_average >= 1 %>
      <div class="votes stats-box shadow">
        <span class="item-count"><%= question.votes_average %></span>
        <div><%= t("questions.units.votes", default: "votes") %></div> 
      </div>
    <% else %>
      <div class="votes stats-box">
        <span class="no-count"><%= t("questions.units.empty", default: "no") %></span>
        <div><%= t("questions.units.votes", default: "votes") %></div> 
      </div>
    <% end %>
    <div style="clear:both"></div>
    <div class="userinfo">
      <%= time_ago(question.created_at) %><%= link_to question.user.name, question.user %> 
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<% if current_tags.any? %>
<div class="selected-tags">
  <span style="font-family: sans-serif; font-size: 20px; margin: 0 6px;">Tagged</span>
  <% current_tags.each do |tag| -%>
    <div class="input-prepend input-append tag">
      <span class="add-on tag-name"><%= tag_name(tag) %></span>
      <span class="add-on remove-tag"><%= link_to 'x', tagged_with_questions_path(tag, true) %></span>
    </div>
  <% end -%>
</div>
<% end -%>
<div class="box box_gray">
  <div id="sort_tabs" class="pagination">
    <div style="display: inline; margin-left: 10px; color: #7EA9B3;"><h3 style="display: inline;"><%= @questions.count %> questions</h3></div>
    <ul class="tab_pos">
      <li><span><%= t("menu.sorts.title", default: "Sort by") %> »</span></li>
      <% [:newest, :activity, :answers, :hot, :votes].each do |order| -%>
        <% if order == current_order_name -%>
          <li class="active"><%= link_to "#{t("menu.sorts.#{order}", default: "#{order.to_s.humanize}")}▼", questions_path(order: order) %></li>
        <% else -%>
          <li><%= link_to t("menu.sorts.#{order}", default: "#{order.to_s.humanize}"), questions_path(order: order) %></li>
        <% end -%>
      <% end -%>
    </ul> 
  </div>
  
  <div class="questions">
    <%= render @questions %>  
  </div>
  <div id="questions-pagination"><%= paginate @questions %></div>
  <% if current_tags.any? -%>
    <div class="alert alert-info">
          Did not find what you were looking for? 
      <%= link_to "Please, post your question!", new_question_path %>
    </div>
  <% end -%>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<!--question -->
<div class="box main-question" id="question-<%= @question.id %>">
  <div class="row-fluid">
    <div class="span1 vote-box-parent">
      <%= render "shared/vote_box", votable: @question, url: question_votes_path(@question) %>
    </div>
    <div class="span11" style="margin-left: 0px;">
      <h3><%= @question.title %></h3>
      <div class="tags">          
        <% @question.tags.each do|tag| -%>
          <%= link_to tag, tagged_with_questions_path(tag), class: "tag" %>
        <% end -%>
      </div>
      <div>
        <%= render "shared/user_info", param: @question -%>  
        <%= markdown @question.body %>
      </div>

      <!--Comments-->
      <div class="comments">
        <div class="comment-items" id="<%= @question.id %>-comments">
          <%= render @question.comments -%>  
        </div>    
        <% if can? :create, Comment -%>
          <div class="comment">
            <label>post a comment</label>
            <div class="comment-form" style="display: none;">
              <%= render "comments/form", form_url: question_comments_path(@question) %>
            </div>
          </div>
        <% end -%>
      </div>
    </div>
  </div>
  <div class="row-fluid question-actions">
  <% if can? :update, @question -%>
    <%= link_to t("common.edit", default: "Edit"), edit_question_path(@question), class: "btn btn-small btn-primary" %>
  <% end -%>
  <% if can? :destroy, @question -%>
    <%= link_to t("common.delete", default: "Delete"), question_path(@question), method: :delete, 
      data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, 
      class: "btn btn-small btn-danger" %>
  <% end -%>
  <% if can? :follow, @question -%>
    <% followed = @question.followed_by?(current_user) -%>
    <%= link_to (followed ? t("common.unfollow", default: "Unfollow") : t("common.follow", default: "Follow")), "#", 
      data: { url: follow_question_path(@question), status: followed }, 
      class: "btn btn-small btn-primary follow-question" %>  
  <% end -%>
  </div>
</div>

<!--answers-->    
<div id="question-answers">
  <div class="answers-tab row-fluid">
    <span id="answers-count" class="title"><%= t("menu.answers.title", answers: @question.answers.count) %></span>
    <div id="sort_tabs" class="pagination">
      <ul>
        <li><span><%= t("menu.sorts.title", default: "Sort by") %> »</span></li>  
        <% [:newest, :oldest, :votes].each do |order| -%>
          <% if order == current_order_name -%>
            <li class="active"><%= link_to "#{t("menu.sorts.#{order}", default: "#{order.to_s.humanize}")}▼", question_path(@question, order: order) %></li>
          <% else -%>
            <li><%= link_to "#{t("menu.sorts.#{order}", default: "#{order.to_s.humanize}")}▼", question_path(@question, order: order) %></li>
          <% end -%>
        <% end -%>
      </ul> 
    </div>
  </div>
  <% if !@answers.empty?-%>
    <% if @question.accepted  %>
      <%= render "answers/answer", answer: @question.answered_with %>
    <% end -%>
    <% @answers.each do |answer| %>
      <% next if answer == @question.answered_with -%>
      <%= render "answers/answer", answer: answer %>
    <% end -%>
  <% end -%>
</div>

<div class="row-fluid" id="answers-pagination"><%= paginate @answers %></div>

<!--answer box -->
<% if can? :create, Answer -%>
<div>
  <h3><%= t("menu.answers.answer_text", default: "Your Answer") %></h3>
  <%= render "answers/form" %>
</div>
<% else -%>
  <%= render :partial => "shared/need_login", locals: {prompt_message: "回答"} %>
<% end -%>

<div id="edit_answer_form_modal" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
    <h4>编辑答案</h4>
  </div>
  <div class="modal-body">
    
  </div>
</div>

app/views/questions/solve.js.erb
$('#question-answers').find('.answer').remove();
$('#question-answers').append('<%= escape_javascript(render @question.answers) %>');

app/views/questions/unsolve.js.erb
$('#question-answers').find('.answer').remove();
$('#question-answers').append('<%= escape_javascript(render @question.answers) %>');