config/routes.rb
require 'sidekiq/web'
  
Ask::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  resources :notifications, :only => [:index, :destroy]
  
  resources :tags
  resources :badges, only: [:index, :show]
  
  post 'markdown/preview' => "application#preview"
  
  resources :photos, only: [:create]
      
  resources :questions do
    resources :comments, :only => [:create, :destroy]
    resources :votes, :only => [:create]
    collection do 
      post :preview
      get '/:tags' => 'questions#index', as: :tagged_with, constraints: { tags: /tags\:(.*)/ }
      get '/:filter' => 'questions#index', :as => :filtered, 
        :constraints => { :filter => /all|unanswered|by_me|feed|preferred|contributed|expertise/ }
    end
    
    member do      
      post :follow
      post :solve
      post :unsolve
    end
    
    resources :answers, :only => [:create, :update, :destroy] do
      resources :comments, :only => [:create, :destroy]
      resources :votes, :only => [:create]
      member do
      end
    end
  end

  root :to => 'questions#index'

  devise_for :users, :controllers => { 
    omniauth_callbacks: "users/omniauth_callbacks", 
    registrations: "users" 
  }
  
  devise_scope :user do
    resources :users, :only => [:show] do
      member do
        post :follow
      end
      collection do
        get "auth/:provider/unbind", to: :auth_unbind, as: :unbind_auth
        get 'avatar'
        put 'crop'
      end
    end
  end

  

end

app/models/notification.rb
class Notification
  include Mongoid::Document
  include Mongoid::Timestamps

  field :read, default: false
  field :source_type, type: String
  field :source_id, type: String
  
  belongs_to :user
  
  validates_presence_of :source_type, :source_id, :user_id
  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    if current_user
      @notifications = current_user.notifications
      current_user.read_notifications(@notifications)
    
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @notifications }
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def get_instance(item)
    item.source_type.classify.constantize.find(item.source_id)
  rescue
    nil
  end
end

app/views/notifications/index.html.erb
<div class="page-header">
  <h1><%=t 'mongoid.models.notification', :default => Notification.model_name.human.pluralize %></h1>
</div>

<div id="notifications">
  <table class="table table-bordered table-striped table-condensed">
    <thead>
      <tr class="head">
        <td>Title</td>
        <td>Notify</td>
        <td>创建时间</td>
        <td class="opts"></td>
      </tr>
    </thead>
    <tbody>
      <% @notifications.each do |item| %>
        <% notify = get_instance(item) %>
        <tr class="<%= cycle("","even") %>">
        <% if  notify != nil && item.source_type == "Answer" -%>
          <td><%= link_to notify.question.title, question_path(notify.question) %></td>
          <td>
            <%= notify.body %>
          </td>
          <td><%= l(item.created_at, :format => :long) %></td>
          <td>
            <%= link_to notification_path(item.id),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' do %>
              <i class="icon-trash"></i><%= t('.destroy', :default => t("helpers.links.destroy")) %>
            <% end %>
          </td>
        <% elsif notify != nil && item.source_type == "Comment" -%>
          <% if notify.commentable.instance_of?(Question) %>
            <td><%= link_to notify.commentable.title, question_path(notify.commentable) %></td>
          <% else %>
            <td><%= link_to notify.commentable.question.title, question_path(notify.commentable.question) %></td>
          <% end %>
          <td>
            <%= notify.body %>
          </td>
          <td><%= l(item.created_at, :format => :long) %></td>
          <td>
            <%= link_to notification_path(item.id),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' do %>
              <i class="icon-trash"></i><%= t('.destroy', :default => t("helpers.links.destroy")) %>
            <% end %>
          </td>
        <% end -%>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/notifications/new.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Notification.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notifications/show.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => Notification.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  </dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              notifications_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_notification_path(@notification), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              notification_path(@notification),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>