config/routes.rb
require 'sidekiq/web'
  
Ask::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  resources :notifications, :only => [:index, :destroy]
  
  resources :tags
  resources :badges, only: [:index, :show]
  
  post 'markdown/preview' => "application#preview"
  
  resources :photos, only: [:create]
      
  resources :questions do
    resources :comments, :only => [:create, :destroy]
    resources :votes, :only => [:create]
    collection do 
      post :preview
      get '/:tags' => 'questions#index', as: :tagged_with, constraints: { tags: /tags\:(.*)/ }
      get '/:filter' => 'questions#index', :as => :filtered, 
        :constraints => { :filter => /all|unanswered|by_me|feed|preferred|contributed|expertise/ }
    end
    
    member do      
      post :follow
      post :solve
      post :unsolve
    end
    
    resources :answers, :only => [:create, :update, :destroy] do
      resources :comments, :only => [:create, :destroy]
      resources :votes, :only => [:create]
      member do
      end
    end
  end

  root :to => 'questions#index'

  devise_for :users, :controllers => { 
    omniauth_callbacks: "users/omniauth_callbacks", 
    registrations: "users" 
  }
  
  devise_scope :user do
    resources :users, :only => [:show] do
      member do
        post :follow
      end
      collection do
        get "auth/:provider/unbind", to: :auth_unbind, as: :unbind_auth
        get 'avatar'
        put 'crop'
      end
    end
  end

  

end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Votable
  
  field :body, type: String  
  
  belongs_to :user,     inverse_of: :answers, counter_cache: true
  belongs_to :question, inverse_of: :answers, counter_cache: true

  embeds_many :comments, as: :commentable, cascade_callbacks: true 
  
  validates_presence_of :body
  validates_length_of :body, minimum: 5
  
  validates_presence_of :user_id
  validates_presence_of :question_id

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  before_filter :find_question
  
  # POST /answers
  # POST /answers.json
  def create
    authorize! :create, Answer
    @answer = @question.answers.build(params[:answer])
    @answer.user = current_user
    if @answer.save
      @msg = t("alert.answer.create_success", default: 'Answer was successfully created.')
    else
      @msg = @answer.errors.full_messages.join("<br />")
    end
  end
  
  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = @question.answers.find(params[:id])
    authorize! :update, @answer
    
    if @answer.update_attributes(params[:answer])
      @msg = t("alert.answer.update_success", default: 'Update Successful.')
    else
      @msg = @error = @answer.errors.full_messages.join("<br />")
    end   
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = @question.answers.find(params[:id])
    authorize! :destroy, @answer
    @answer.destroy
    
    head :no_content
  end
  
  protected

    def find_question
      @question = current_node.questions.find(params[:question_id])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="box answer" id="answer-<%= answer.id %>">
  <div class="row-fluid">
    <div class="span1 vote-box-parent">
      <%= render "shared/vote_box", votable: answer, url: question_answer_votes_path(@question, answer) %>
    </div>
    <div class="span11" style="margin-left: 6px;">
      <%= render "shared/user_info", param: answer -%>
      <div class="answer-content">
        <%= markdown answer.body %>
      </div>
      <div class="row-fluid answer-actions">
      <% if can? :update, answer -%>
        <%= link_to t("common.edit", default: "Edit"), "#edit_answer_form_modal", data: { toggle: "modal", keyboard: true, backdrop: true }, 
          class: "btn btn-small btn-primary edit-answer-button" %>
        <div class="edit-answer-form">
          <%= render "answers/form", answer: answer %>
        </div>
      <% end -%>
      <% if can? :destroy, answer -%>
        <%= link_to t("common.delete", default: "Delete"), question_answer_path(@question, answer), remote: true, method: :delete, 
          data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, 
          class: "btn btn-small btn-danger" %>
      <% end -%>
      <% show_solve = !@question.answered_with && (can? :solve, @question) -%>
      <% show_unsolve = @question.answered_with == answer && (can? :unsolve, @question)-%>
      <%= link_to t("common.solution"), solve_question_path(@question, answer_id: answer), remote: true, 
        method: 'post', class: "btn btn-small btn-primary solve-link#{show_solve ? '' : ' hide'}" %>  
      <%= link_to t("common.cancel_solution"), unsolve_question_path(@question, answer_id: answer), remote: true, 
        method: 'post', class: "btn btn-small btn-primary unsolve-link#{show_unsolve ? '' : ' hide'}" %>     
      </div>
      <!--Comments-->
      <div class="comments">
        <div class="comment-items" id="<%= answer.id %>-comments">
          <%= render answer.comments -%>
        </div>
        <% if can? :create, Comment -%>
          <div class="comment">
            <label>post a comment</label>
            <div class="comment-form" style="display: none;">
              <%= render "comments/form", form_url: question_answer_comments_path(@question, answer) %>
            </div>
          </div>
        <% end -%>
      </div>
    </div>
  </div>
</div>

app/views/answers/_form.html.erb
<div class="answer-form-box">
<% answer ||= Answer.new %>
<%= simple_form_for([@question, answer], remote: true) do |f| %>
  <%= render "shared/error_messages", :target => answer  %>
  <fieldset>
    <div class="control-group edit_tools">
      <label class="control-label"></label>
      <div class="controls">
        <%= render "questions/editor_toolbar" %>
      </div>
    </div>
    <%= f.input :body, as: :text, label: false, input_html:{ :class => "answers_editor closewarning xxlarge", :style => "height:200px" } %>
    <%= f.input :question_id, :as => :hidden, :input_html => { :value => @question.id } %>
    <div class="form-actions">
      <%= f.submit t("common.save"), :class => "btn btn-primary" %>
      <%= link_to t("common.cancel"), question_path(@question), :class => "cancel-link btn", data: {dismiss: "modal"} %>
    </div>
  </fieldset>
<% end %>

  <div class="hide">
  <%= simple_form_for Photo.new, html: { class: "form-inline upload-photo-form" } do |f| %>
    <%= f.input :image, label: false, input_html: { class: "upload-photo-images" } %>
  <% end %>
  </div>
</div>

app/views/answers/create.js.erb
<% if @answer.errors.blank? -%>
  $("#question-answers").append('<%= escape_javascript(render(@answer)) %>')
    .find("#answers-count b").text('<%= @question.answers_count + 1%>');
  Questions.hookAnswersCallback('#question-answers .answer:last');
  Questions.hookCommentsCallback('#question-answers .answer:last');
  Questions.answerCallback(true, '<%= escape_javascript(@msg) %>');
<% else -%>
  Questions.answerCallback(false, '<%= escape_javascript(@msg) %>');
<% end -%>

app/views/answers/edit.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Answer.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/answers/update.js.erb
var _id = '#<%= @answer.class.to_s.underscore %>-<%= @answer.id %>';
<% if @error -%>
  Util.alert('<%= @msg %>', _id + " > div:first");
<% else -%>
  $("#edit_answer_form_modal").modal('hide');
  $(_id).find(".answer-content").html('<%= escape_javascript(markdown(@answer.body)) %>');
  $(_id).find(".edit-answer-form").find('textarea.answers_editor').text('<%=raw escape_javascript(@answer.body) %>');
  Util.notice('<%= @msg %>', _id + " > div:first");
<% end -%>