config/routes.rb
require 'sidekiq/web'
  
Ask::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  resources :notifications, :only => [:index, :destroy]
  
  resources :tags
  resources :badges, only: [:index, :show]
  
  post 'markdown/preview' => "application#preview"
  
  resources :photos, only: [:create]
      
  resources :questions do
    resources :comments, :only => [:create, :destroy]
    resources :votes, :only => [:create]
    collection do 
      post :preview
      get '/:tags' => 'questions#index', as: :tagged_with, constraints: { tags: /tags\:(.*)/ }
      get '/:filter' => 'questions#index', :as => :filtered, 
        :constraints => { :filter => /all|unanswered|by_me|feed|preferred|contributed|expertise/ }
    end
    
    member do      
      post :follow
      post :solve
      post :unsolve
    end
    
    resources :answers, :only => [:create, :update, :destroy] do
      resources :comments, :only => [:create, :destroy]
      resources :votes, :only => [:create]
      member do
      end
    end
  end

  root :to => 'questions#index'

  devise_for :users, :controllers => { 
    omniauth_callbacks: "users/omniauth_callbacks", 
    registrations: "users" 
  }
  
  devise_scope :user do
    resources :users, :only => [:show] do
      member do
        post :follow
      end
      collection do
        get "auth/:provider/unbind", to: :auth_unbind, as: :unbind_auth
        get 'avatar'
        put 'crop'
      end
    end
  end

  

end

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :description, type: String
  field :count, type: Integer
  
  field :_id, type: String, default: ->{ name.try(:parameterize) }

  validates_length_of :name, :minimum => 1  
  validates_uniqueness_of   :name

  belongs_to :user  
  embedded_in :node, :inverse_of => :tags

  def self.list
    all.map(&:id)
  end

  def question_count
    Question.tagged_with(id).count
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource :only => [:new, :edit, :create, :update, :destroy], :through => :current_node
  respond_to :html, :json
  
  # GET /tags
  # GET /tags.json
  def index
    @tags = current_node.tags
    respond_with @tag
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = current_node.tags.find(params[:id])
    respond_with @tag
  end

  # GET /tags/new
  # GET /tags/new.json
  def new    
#    authorize! :create, Tag
#    @tag = current_node.tags.build    
    respond_with @tag
  end

  # GET /tags/1/edit
  def edit
#    @tag = current_node.tags.find(params[:id])    
    authorize! :update, @tag
  end

  # POST /tags
  # POST /tags.json
  def create  
#    authorize! :create, Tag
#    @tag = current_node.tags.build(params[:tag])
    @tag.user_id = current_user.id  
    
    flash[:notice] = "Tag was successfully created." if @tag.save
    respond_with @tag    
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
#    @tag = current_node.tags.find(params[:id])
#    authorize! :update, @tag
    
    flash[:notice] = "Tag was successfully updated." if @tag.update_attributes(params[:tag])
    respond_with @tag 
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
#    @tag = current_node.tags.find(params[:id])
#    authorize! :destroy, @tag
    @tag.destroy
    
    respond_with(@user) do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div id="tag" class="form box">

<%= simple_form_for(@tag) do |f| %>
  <%= render "/shared/error_messages", :target => @tag  %>
  <fieldset>
    <legend><%= t("common.edit") %> Tag</legend>
      <%= f.input :name %>
      <%= f.input :description, as: :text, input_html:{ class: "xxlarge", style: "height: 100px"} %>
      <div class="form-actions">
      <%= f.submit t("common.save"), :class => "btn btn-primary" %> or <%= link_to t("common.cancel"), tags_path %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<div class="page-header">
  <h1><%= t("menu.tags", default: "Tags") %></h1>
</div>
<div id="tags">
  <table class="table">
    <% @tags.each_slice(4) do |tag_tr| %>
      <tr>
        <% tag_tr.each do |tag| %>
          <td style="border-top: 0px;">
            <%= link_to tag.name, tag_path(tag), class: "tag_table" %> <span>x <%= tag.question_count %></span> 
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<div class="tools">
  <%= link_to t('common.new'),
              new_tag_path,
              :class => 'btn btn-mini btn-primary' %>
</div>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<div class="row box">
  <%= render Question.tagged_with(@tag.id) %>  
</div>